add fee_sats_per_tx
Fixes this error

     Running `target/debug/sapio-cli contract create 9.99 '{"participants": [{"amount": 9.99, "address": "bcrt1qs758ursh4q9z627kt3pp5yysm78ddny6txaqgw"}], "radix": 2}' --file=plugin-example/pkg/sapio_wasm_plugin_example_bg.wasm`
Error: Required properties "fee_sats_per_tx" are missing
At instance path /:
  {
    "participants": [
      {
        "address": "bcrt1qs758ursh4q9z627kt3pp5yysm78ddny6txaqgw",
        "amount": 9.99
      }
    ],
    "radix": 2
  }

At schema path /required:
  [
    "fee_sats_per_tx",
    "participants",
    "radix"
  ]